username: admin
password: coffee

chargify_key: bXt3MAoT6-bwf8gitwqd
chargify_domain: castle-protection

gmkey: ABQIAAAASWEk1UdvToR0DcvOwCMx7xTlohoRC1KUZQN04oJlg35Jxm-N9RQPkzSSJfKHSxWKr90pRsTdoRDKSA

gmail_username: 'cube2media@gmail.com'
gmail_password: 'coffee*8'