username: admin
password: coffee

gmkey: ABQIAAAASWEk1UdvToR0DcvOwCMx7xTlohoRC1KUZQN04oJlg35Jxm-N9RQPkzSSJfKHSxWKr90pRsTdoRDKSA

gmail_username: 'cube2media@gmail.com'
gmail_password: 'rockstar*8'

app_name: "Castle Protection, Inc."
service_states: "Colorado, Indiana, Kansas, Kentucky, Missouri, New Hampshire, North Dakota, Ohio, Pennsylvania, South Dakota, Wisconsin, and Texas"

order_email: "Josh Luttrell <jl.psi@sbcglobal.net>, Cube2Media Support <support@cube2media.com>"

# Old Gateway Values
# merchant_id: 65628
# merchant_id: 33163
# reg_key: "9WEB79RSQYB9Q9N7"
# process_fee: 30
# recurring_url: https://webservices.primerchants.com/billing/TransactionCentral/AddRecurring.asp?
# charge_description: "Castle Protection Subscription Fee"
# single_charge_url: https://webservices.primerchants.com/billing/TransactionCentral/processCC.asp?


# Stripe API Key TEST Keys
stripe_key: fdZrjkd34GBTUNJpT0cGGI3BQBNf2VCQ
stripe_publish_key: pk_vR3sSsukToxICYJ9RZaU8Zoq3qsXP

# Addon rates
process_fee: 30
tax_rate: 0.0825