username: admin
password: coffee

chargify_key: bvqvqu3b8696unZSGRkc
chargify_domain: cube2media
chargify_free: warranty-free
chargify_plus: warranty-plus
chargify_premium: warranty-premium

gmkey: ABQIAAAASWEk1UdvToR0DcvOwCMx7xTlohoRC1KUZQN04oJlg35Jxm-N9RQPkzSSJfKHSxWKr90pRsTdoRDKSA

gmail_username: 'cube2media@gmail.com'
gmail_password: 'coffee*8'