username: admin
password: coffee

gmkey: ABQIAAAASWEk1UdvToR0DcvOwCMx7xTlohoRC1KUZQN04oJlg35Jxm-N9RQPkzSSJfKHSxWKr90pRsTdoRDKSA

gmail_username: 'cube2media@gmail.com'
gmail_password: 'coffee*8'

app_name: "Castle Protection LLC."

order_email: "Josh Luttrell <jl.psi@sbcglobal.net>, Cube2Media Support <support@cube2media.com>"

# merchant_id: 65628
merchant_id: 33163
reg_key: "9WEB79RSQYB9Q9N7"
process_fee: 0.01
recurring_url: https://webservices.primerchants.com/billing/TransactionCentral/AddRecurring.asp?
charge_description: "Castle Protection Subscription Fee"
single_charge_url: https://webservices.primerchants.com/billing/TransactionCentral/processCC.asp?
